name: Build Docker Images

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubicloud-standard-2-arm
    concurrency: build-docker-images
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: jahands
      EARTHLY_SATELLITE: mini-sat
      FORCE_COLOR: 1
    steps:
      - name: Extract Branch Name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: earthly/actions-setup@v1.0.11
        with:
          version: v0.8.6
      - uses: actions/checkout@v2
      - name: 'Docker: Base Image'
        run: earthly --ci --push +docker-baseimage
      - name: 'Docker: Base Image (GUI)'
        run: earthly --ci --push +docker-baseimage-gui
      - name: 'Docker: Thunderbird'
        run: earthly --ci --push +docker-thunderbird
