name: Build Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubicloud-standard-2
    concurrency: build-docker-images
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: jahands
      EARTHLY_SATELLITE: mini-sat
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1.0.11
        with:
          version: v0.8.6
      - uses: actions/checkout@v4
      - name: 'Docker: Base Image'
        run: earthly --ci --push +docker-baseimage
      - name: 'Docker: Base Image (GUI)'
        run: earthly --ci --push +docker-baseimage-gui
      - name: 'Docker: Thunderbird'
        run: earthly --ci --push +docker-thunderbird
