name: CI with Earthly

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubicloud-standard-2-arm
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: jahands
      EARTHLY_SATELLITE: xs-sat
      FORCE_COLOR: 1
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.3
      - uses: actions/checkout@v2
      - name: 'Docker: Base Image'
        run: earthly --ci --push +docker-baseimage
      - name: 'Docker: Base Image (GUI)'
        run: earthly --ci --push +docker-baseimage-gui
      - name: 'Docker: Thunderbird'
        run: earthly --ci --push +docker-thunderbird
